### PR TITLE
Add coveralls script to package.json

### PR DESCRIPTION
**Pull request by cristiancavalli**
Add support for coveralls

### CODE REVIEW

**Comment by cristiancavalli** [comment]
@ofrobots @matthewloring PTAL

**Comment by matthewloring** [comment]
We will want to get coverage runs going on travis. It can be set up in the travis yaml but it may be easier to emulate the scripts in the trace or debug bin directory.

**Comment by cristiancavalli** [comment]
@matthewloring I just modified the travis.yml file to use the coveralls script which is the same test script just with the output routed to coveralls. This has been tested to work locally when given the correct env variables and the output showed up in coveralls.

**Comment by ofrobots** [comment]
LGTM. 100%?? :dizzy:

**Pull request merged**
