### PR TITLE
Specify lodash dependencies over full library

### PR DESCRIPTION
**Pull request by cristiancavalli**
Specify only required lodash submodules in both
dependencies and development dependencies.

### CODE REVIEW

**Comment by cristiancavalli** [comment]
@ofrobots @matthewloring ptal

**Comment by ofrobots** [comment]
`request` depends on full `lodash` so wouldn't actually end up increasing the disk footprint?

**Comment by cristiancavalli** [comment]
@ofrobots I don't see that in the deps on the GH page:
https://github.com/request/request/blob/master/package.json

Am I missing it?

**Comment by ofrobots** [comment]
Apologies. The dependency chain as per `yarn`: `@google/cloud-errors#@google/cloud-diagnostics-common#google-auth-library#request#form-data#async`

**Comment by cristiancavalli** [comment]
Ahh, my bad. I'll close this pr.

**Comment by ofrobots** [comment]
Thanks for putting this together though!

**Pull request closed without merging**
