### PR TITLE
remove local development instructions

### PR DESCRIPTION
**Pull request by steren**

### CODE REVIEW

**Comment by matthewloring** [comment]
I don't think this should be removed. These instructions also hold for users hosting their apps in production outside of GCP. Maybe it could be renamed to `Running Elsewhere`?

**Comment by steren** [comment]
Yes I agree the section is not well named, as we say explicitely that the environment should be set to 'production'

I think the README should not assume the user is running on GCP and should contains instructions for running anywhere, and this is what I suggest in https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/9

I suggest to add a new section that details the configuration behavior:
Which environment variables are used and how the various ways to authenticate. What do you think? 

I will do it in this PR if we agree.

**Comment by ofrobots** [comment]
The README.md, in general, needs a fair amount of restructuring to make it flow and sound great. The objective for the current one was to get something basic in place.

I expect there would be some iteration (a.k.a bike-shedding) before it gets to a state that everyone is happy with. @steren: It sound like you're willing to take a stab at driving this overall?

**Comment by steren** [comment]
Yes I can drive having a first version of the README, I will loop you in.

**Pull request merged**
